name: Build ZMK

on: [pull_request, workflow_dispatch, push]

jobs:
  adjust-branch-name:
    runs-on: ubuntu-22.04
    outputs:
      BRANCH: ${{ steps.branch.outputs.BRANCH }}
    steps:
      - run: |
          branch='${{ github.ref_name }}'
          if [ ${{ github.event == 'pull_request' }} ]; then
            branch='${{github.head_ref}}'
          fi;

          echo "github.ref_name = ${{ github.ref_name }}"
          echo "github.ref = ${{ github.ref }}"

          echo "branch name = $branch"

          echo "BRANCH=$branch" >> $GITHUB_OUTPUT
        id: branch

  build-zmk:
    needs: adjust-branch-name
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      archive_name: firmware-${{ needs.adjust-branch-name.outputs.BRANCH }}-${{ github.run_id }}
