name: Build ZMK

on: [pull_request, workflow_dispatch, push]

jobs:
  adjust-branch-name:
    runs-on: ubuntu-22.04
    outputs:
      BRANCH: ${{ steps.branch.outputs.BRANCH }}
    steps:
      - run: |
          if [ ${{ github.event == 'pull_request' }} ]; then
            echo "Using PR head_ref"
            branch=${{ github.head_ref }}
          else
            echo "Not in PR. Using ref_name"
            branch=${{ github.ref_name }}
          fi;

          echo "branch = $branch"

          echo "BRANCH=$branch" >> $GITHUB_OUTPUT
        id: branch

  build-zmk:
    needs: adjust-branch-name
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      archive_name: firmware-${{ needs.adjust-branch-name.outputs.BRANCH }}-${{ github.run_id }}
